maximum_name_length: 50
maximum_email_length: 250
minimum_password_length: 6
remember_checked_default_value: "1"
default_gravatar_url: "https://secure.gravatar.com/avatar/"
default_gravatar_size: 80
max_user_query_per_page: 25
max_micropost_per_page: 5
max_item_per_page: 5
maximum_password_reset_time: 2
maximum_content_length: 140
max_image_size: 8
img_rsize_width: 400
img_rsize_height: 400
